[package]
name = "lace_consts"
version = "0.1.4"
authors = ["Promied AI"]
edition = "2021"
license = "SSPL-1.0"
homepage = "https://www.lace.dev/"
repository = "https://github.com/promised-ai/lace"
description = "Default constants for Lace"

[dependencies]
# rv = { version = "0.16.0", features = ["serde1", "arraydist"] }
# rv = { git = "https://gitlab.com/baxe/rv.git", branch="feature/experimental", features = ["serde1", "arraydist", "experimental"] }
rv = { path="/Users/bax/Documents/redpoll/rv", features = ["serde1", "arraydist", "experimental"] }
