[package]
name = "pylace"
version = "0.3.0"
edition = "2021"
license = "SSPL-1.0"

[lib]
name = "lace"
crate-type = ["cdylib"]

[dependencies]
lace = { path = "../lace", version="0.3.0" }
lace_utils = { path = "../lace/lace_utils", version="0.1.2" }
rand = "0.8.5"
rand_xoshiro = "0.6.0"
pyo3 = { version = "0.19", features = ["extension-module"] }
serde_json = "1.0.91"
serde_yaml = "0.9.17"
polars = "0.31"
arrow2 = "0.17"

[package.metadata.maturin]
name = "lace.core"
